version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: kitten
      POSTGRES_USER: kitten
      POSTGRES_PASSWORD: kitten
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py loaddata backup_utf8.json &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8000:8000"
